# Site settings
title: Phu Ha
twitter_username: vinhphu3000
name: Phu Ha

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://vinhphu3000.blogspot.com
 - title: GitHub
   url: https://github.com/vinhphu3000
 - title: StackOverflow
   url: http://stackoverflow.com/users/877209/vinhphu3000

#Any buzzword skills you want to include
skills:
  - Java
  - Project Management  

#Work experience is required
roles:
 - title: Technical Project Manager
   start: May 2018
   end: Now
   employer: <a href="https://linepluscorp.com/">LINE Plus Corp.</a>
   description: Technical Project Manager, Delivery Management
 - title: Head of Development (Vietnam)
   start: Sep 2014
   end: Jul 2018
   employer: <a href="https://www.magnolia-cms.com/">Magnolia CMS</a>
   description: Software Engineering
 - title: Project Management
   start: Nov 2011
   end: Sep 2014
   employer: <a href="https://www.nashtechglobal.com/visit-vietnam/"></a>
   description: Project Management, Line Management, Bid Management
 - title: Principal Software Engineer
   start: Apr 2005
   end: Nov 2011
   employer: <a href="http://www.dxc.technology/vn_vn">DXC Vietnam</a>
   description: Software Engineer, Acting Project Manager
 - title: Java Developer
   start: Oct 2003
   end: Apr 2005
   employer: <a href="http://raovat.net">SGC - an Internet Company</a>
   description: Java Developer

#Education is required
education:
 - level: Professional Scrum Master™
   date: 2015
   subject: 
   school: 
 - level: PMP Candidate
   date: 2013
   subject: 
   school: PMI
 - level: Bachelor of Science
   date: 2003
   subject: Information System
   school: University of Natural Science
