# Site settings
title: Phu Ha
twitter_username: vinhphu3000
name: Phu Ha

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://vinhphu3000.blogspot.com
 - title: GitHub
   url: https://github.com/vinhphu3000
 - title: StackOverflow
   url: http://stackoverflow.com/users/877209/vinhphu3000

#Any buzzword skills you want to include
skills:
 - Groovy
 - Spring MVC
 - Spring Boot
 - Gradle
 - Java
 - JCR
 - SQL
 - REST
 - Tech Architecture

#Work experience is required
roles:
 - title: Senior Technical Project Manager
   start: Sep 2014
   end: Now
   employer: <a href="https://www.pycogroup.com/home">PYCO Group - Pyramid Consulting Vietnam</a>
   description: Project Manager, Technical Manager, Operation Manager
 - title: Project Manager
   start: Nov 2011
   end: Sep 2014
   employer: <a href="http://www.harveynash.com/vn/">Harvey Nash Vietnam</a>
   description: Project Manager, Resource Manager, Bid Manager
 - title: Business Development Manager
   start: Oct 2010
   end: Nov 2011
   employer: FPT Promo (later acquired by <a href="https://www.fpt-software.com/">FPT Software</a>)
   description: Partnership Manager, Account Manager, Digital Project Manager
 - title: Principal Software Engineer
   start: Apr 2005
   end: Oct 2010
   employer: CSC Vietnam (later merged into HP became <a href="http://www.dxc.technology/vn_vn">DXC</a>)
   description: Software Developer, Technical Lead, Acting Project Manager
 - title: Software Developer at various companies
   start: Sep 2003
   end: Apr 2005
   employer: <a href="http://raovat.net">SGC - an Internet Company</a>; <a href="http://sutrixgroup.com/">Sutrix Media</a>
   description: Software Developer

#Education is required
education:
 - level: Professional Scrum Master™
   date: 2015
   subject: 
   school: 
 - level: PMP Candidate
   date: 2013
   subject: 
   school: PMI
 - level: Bachelor of Science
   date: 2003
   subject: Information System
   school: University of Natural Science
