# Site settings
title: Phu Ha
twitter_username: vinhphu3000
name: Phu Ha

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://vinhphu3000.blogspot.com
 - title: GitHub
   url: https://github.com/vinhphu3000
 - title: StackOverflow
   url: http://stackoverflow.com/users/877209/vinhphu3000

#Any buzzword skills you want to include
skills:
 - Groovy
 - Spring MVC
 - Spring Boot
 - Gradle
 - Java
 - JCR
 - SQL
 - REST
 - Tech Architecture

#Work experience is required
roles:
 - title: Development Lead
   start: 2011
   end: Ongoing
   employer: NashTech (BCC Adsystem), PycoGroup (Magnolia CMS under BOT model)
   description: 
 - title: Senior Software Developer
   start: 2008
   end: 2011
   employer: CSC Vietnam, FPTPromo, a subsidairy of FPT Corp.
   description: 
 - title: Software Developer
   start: 2003
   end: 2008
   employer: CSC Vietnam (BakBone lately acquired by QUEST then DELL)
   description: 

#Education is required
education:
 - level: Bachelor of Science
   date: 2003
   subject: Information System
   school: University of Natural Science
